version: '3'

networks:
  to-do-network:
    driver: bridge

volumes:
  sqldata: {}
  logs:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/var/log/'

services:
  mysql:
    image: mysql:5.7
    container_name: db
    restart: always
    env_file: ./services/mysql/.env
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3307:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - sqldata:/var/lib/mysql

  django:
    container_name: django
    build: ./services/django
    env_file: ./services/django/.env
    depends_on:
      - mysql
    networks:
      - to-do-network
    volumes:
      - logs:/fractal_analytics_platform/logs/
    restart: unless-stopped
    labels:
      org.label-schema.group: "fullstack-assignment-platform"

  nginx:
    build: ./nginx
    ports:
      - 1337:80
    networks:
      - to-do-network
    depends_on:
      - django
