version: '3'

volumes:
  sqldata: {}

services:
  mysql:
    image: mysql:5.7
      restart: always
      env_file: services/mysql/.env
      ports:
        # <Port exposed> : < MySQL Port running inside container>
        - '3307:3306'
      expose:
        # Opens port 3306 on the container
        - '3306'
        # Where our data will be persisted
      volumes:
        - sqldata:/var/lib/mysql
